### ISSUE TITLE
Cannot query field "weather" on type "Location".

### ISSUE THREAD

**Issue by saerdnaer** [stubailo/schema-stitching-demo#9]
Looks like the remote schema exchange does not work as explected – any ideas?

![image](https://user-images.githubusercontent.com/40266/36419082-3bc4fefc-1631-11e8-8286-954387001d2f.png)

The weather endpoint itself looks fine to me: https://launchpad.graphql.com/5rrx10z19

![image](https://user-images.githubusercontent.com/40266/36419221-90bd79b6-1631-11e8-836c-8fa4537f5b4d.png)

**Comment by ruwhan** [comment]
facing same issue here.
